apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
        - name: health-api
          image: ${{ env.DOCKER_IMAGE }}:latest
          ports:
            - containerPort: 3000
